Initing queues for: "eth1br"
Created queue dict: {'queueId': 1, 'bw': None, 'nw_src': '10.1.1.3', 'queueuuid': None, 'nw_dst': '10.1.1.8'}
Created queue dict: {'queueId': 2, 'bw': None, 'nw_src': '10.1.1.8', 'queueuuid': None, 'nw_dst': '10.1.1.3'}
ovs-vsctl: row id "@queue2" may only be specified on one --id option
Exception in thread Monitor:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/FlowFenceGit/FlowFence/FlowMonitor.py", line 146, in monitor
    self.completeInterfaceList[j]['queueList']=self.initQueues(self.completeInterfaceList[j]['name'],self.completeFlowList[j]['flowList'])
  File "/root/FlowFenceGit/FlowFence/FlowMonitor.py", line 200, in initQueues
    subprocess.check_output(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'ovs-vsctl -- set Port "eth1br" qos=@testqos -- --id=@testqos create QoS type=linux-htb queues=0=@queue0,1=@queue1,2=@queue2 -- --id=@queue0 create Queue other-config:max-rate=1000000000 -- --id=@queue2 create Queue other-config:max-rate=1000000000 -- --id=@queue2 create Queue other-config:max-rate=1000000000 ' returned non-zero exit status 1

# Ejemplo del manual de ovs-vsctl
ovs-vsctl -- set Port eth0 qos=@newqos \

              -- set Port eth1 qos=@newqos \

              --       --id=@newqos       create       QoS      type=linux-htb
              other-config:max-rate=1000000000 queues=0=@q0,1=@q1 \

              --   --id=@q0   create   Queue   other-config:min-rate=100000000
              other-config:max-rate=100000000 \

              -- --id=@q1 create Queue other-config:min-rate=500000000



 ovs-vsctl -- set Port "eth1br" qos=@testqos -- --id=@testqos create QoS type=linux-htb queues=0=@queue0,1=@queue1,2=@queue2 -- --id=@queue0 create Queue other-config:max-rate=1000000000 -- --id=@queue2 create Queue other-config:max-rate=1000000000 -- --id=@queue2 create Queue other-config:max-rate=1000000000 

 No imprime lisa de queues ndo es invocada, pero se crean aparentemente bien las queues. Falta revisar, por qué se invoca initQueues a cada update?
tE amo  , pero odio tu teclado

 Message Received: {'Interface': '"eth1br"', 'Response': 'Decrement', 'bwList': [{'goodBehaved': True, 'bw': 45000000.0, 'nw_src': '10.1.1.3', 'nw_dst': '10.1.1.8'}, {'goodBehaved': True, 'bw': 45000000.0, 'nw_src': '10.1.1.3', 'nw_dst': '10.1.1.8'}]}
Initing queues for: "eth1br"
Created queue dict: {'queueId': 1, 'bw': None, 'nw_src': '10.1.1.8', 'queueuuid': None, 'nw_dst': '10.1.1.3'}
Created queue dict: {'queueId': 2, 'bw': None, 'nw_src': '10.1.1.3', 'queueuuid': None, 'nw_dst': '10.1.1.8'}
Queue command: 
 ovs-vsctl -- set Port "eth1br" qos=@fenceqos -- --id=@fenceqos create QoS type=linux-htb queues=0=@queue0,1=@queue1,2=@queue2 -- --id=@queue0 create Queue other-config:max-rate=1000000000 -- --id=@queue1 create Queue other-config:max-rate=1000000000 -- --id=@queue2 create Queue other-config:max-rate=1000000000 
Queue List: [{'queueId': 1, 'bw': None, 'nw_src': '10.1.1.8', 'queueuuid': {'id': 1, 'uuid': '5f2e6964-0b25-4983-91e3-88449b932a70'}, 'nw_dst': '10.1.1.3'}, {'queueId': 2, 'bw': None, 'nw_src': '10.1.1.3', 'queueuuid': {'id': 2, 'uuid': '9f8d2099-41ca-4890-b1a0-31935417e615'}, 'nw_dst': '10.1.1.8'}]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "ApplicationSwitch.py", line 52, in run
    self.reportObject.messageFromController(self.received,self.srcAddress)
  File "ApplicationSwitch.py", line 178, in messageFromController
    self.linkState.createQueues(messageDict)
  File "/root/FlowFenceGit/FlowFence/FlowMonitor.py", line 182, in createQueues
    self.setQueuesBw(self.completeInterfaceList[i]['queueList'], controllerMessage['bwList'])
AttributeError: FlowMonitor instance has no attribute 'setQueuesBw'


Type of message QueuesDone
message to be used for redirection{'Flowlist': [{'length': 294, 'oldArrivalRate': 59.506269564418204, 'arrivalRate': 179.2756341588988, 'nw_dst': '10.1.1.3', 'action': 'output:1', 'goodBehaved': None, 'dl_dst': '00:06:0d:a0:10:05', 'packets': 3, 'dl_src': '00:49:d0:b1:21:7c', 'nw_src': '10.1.1.8'}, {'length': 196, 'oldArrivalRate': 0.0, 'arrivalRate': 118.86263491518368, 'nw_dst': '10.1.1.8', 'action': 'LOCAL', 'goodBehaved': 0, 'dl_dst': '00:49:d0:b1:21:7c', 'packets': 2, 'dl_src': '00:06:0d:a0:10:05', 'nw_src': '10.1.1.3'}], 'Notification': 'QueuesDone', 'Interface': {'capacity': 100000000, 'name': '"eth1br"', 'dpid': '"00000049d0b1217c"'}, 'QueueList': [{'queueId': 1, 'bw': None, 'nw_src': '10.1.1.8', 'queueuuid': {'id': 1, 'uuid': '91cf5164-0881-4fdc-b91f-14d50ad782d0'}, 'nw_dst': '10.1.1.3'}, {'queueId': 2, 'bw': None, 'nw_src': '10.1.1.3', 'queueuuid': {'id': 2, 'uuid': '3b7a9234-9997-48df-bbc4-6a7de66a8518'}, 'nw_dst': '10.1.1.8'}]}


This error appears in the FlowFence app at the controller

ERROR:openflow.of_01:[00-49-d0-b1-21-7c 2] OpenFlow Error:
[00-49-d0-b1-21-7c 2] Error: header: 
[00-49-d0-b1-21-7c 2] Error:   version: 1
[00-49-d0-b1-21-7c 2] Error:   type:    1 (OFPT_ERROR)
[00-49-d0-b1-21-7c 2] Error:   length:  76
[00-49-d0-b1-21-7c 2] Error:   xid:     76436
[00-49-d0-b1-21-7c 2] Error: type: OFPET_BAD_REQUEST (1)
[00-49-d0-b1-21-7c 2] Error: code: OFPBRC_BUFFER_UNKNOWN (8)
[00-49-d0-b1-21-7c 2] Error: datalen: 64
[00-49-d0-b1-21-7c 2] Error: 0000: 01 0e 00 50 00 01 2a 94  00 00 00 00 00 01 00 06   |...P..*.........|
[00-49-d0-b1-21-7c 2] Error: 0010: 0d a0 10 05 00 49 d0 b1  21 7c ff ff 00 00 08 00   |.....I..!|......|
[00-49-d0-b1-21-7c 2] Error: 0020: e0 11 00 00 0a 01 01 1f  0a 01 02 02 86 b2 65 67   |..............eg|
[00-49-d0-b1-21-7c 2] Error: 0030: 00 00 00 00 00 00 00 00  00 00 00 0a 00 1e 80 00   |................|


switch dpid 317033881980
switch dpid 783707765714


pdc-1 eth0br
dpid:000000b6789f7bd2
783707765714


pdc-1 ethbr
dpid:00000049d0b1217c
317033881980            !!!


pdc-2 eth0br
dpid:000000b5739f7bd1

pdc-2 eth1br
dpid:00000049d0c2217e

Usando "dpidToStr tenemos: "

switch dpid 317034996094
Hex dpid: 00-49-d0-c2-21-7e
switch dpid 779328912337
Hex dpid: 00-b5-73-9f-7b-d1

tarán!!!


dpid parameter: "00000049d0b1217c"
Connection dpid: 317034996094
Real dpidStr: 0049d0c2217e
Connection dpid: 779328912337
Real dpidStr: 00b5739f7bd1
Connection dpid: 317033881980
Real dpidStr: 0049d0b1217c
Connection dpid: 783707765714
Real dpidStr: 00b6789f7bd2


a[len(nocoma)-13:]
[:len(corrected)-1]

dpid parameter: 049d0b1217c"
Connection dpid: 779328912337
Real dpidStr: 00b5739f7bd1
Connection dpid: 317034996094
Real dpidStr: 0049d0c2217e
Connection dpid: 317033881980
Real dpidStr: 0049d0b1217c
Connection dpid: 783707765714
Real dpidStr: 00b6789f7bd2
Well...done





Flow mod message: ofp_flow_mod
  header:
    version: 1
    type:    14 (OFPT_FLOW_MOD)
    length:  88
    xid:     24
  match:
    wildcards: nw_tos|tp_dst|dl_dst|dl_src|in_port|dl_vlan_pcp|nw_proto|dl_vlan|tp_src (1100000000000011101111 = 3000ef)
    dl_type: 0x800
    nw_src: 10.1.1.8
    nw_dst: 10.1.1.3
  cookie: 0
  command: 0
  idle_timeout: 0
  hard_timeout: 0
  priority: 65535
  buffer_id: None
  out_port: 65535
  flags: 0
  actions:
    type: 11
    len: 16
    port: 1
    queue_id: 1


0xffffffff
bufferid = -1

# Seen somewhere in the net
 msg.buffer_id = event.ofp.buffer_id




 
 Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/pox/ext/FlowFence.py", line 92, in run
    self.handleFlowsRedirection(message['Interface']['dpid'],self.myconnections, self.srcAddress, message)
  File "/root/pox/ext/FlowFence.py", line 206, in handleFlowsRedirection
    connection.send(msg)
  File "/root/pox/pox/openflow/of_01.py", line 692, in send
    data = data.pack()
  File "/root/pox/pox/openflow/libopenflow_01.py", line 2322, in pack
    packed += i.pack()
  File "/root/pox/pox/openflow/libopenflow_01.py", line 1603, in pack
    packed += struct.pack("!HHH", self.type, len(self), self.port)
error: cannot convert argument to integer
